//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MD.BRIDGE.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MD.BRIDGE.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string Button_Apply {
            get {
                return ResourceManager.GetString("Button_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        public static string Button_Connect {
            get {
                return ResourceManager.GetString("Button_Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string Button_Download {
            get {
                return ResourceManager.GetString("Button_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string Button_Stop {
            get {
                return ResourceManager.GetString("Button_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect server to download.
        /// </summary>
        public static string Footer_ConnectServerToDownloadMessage {
            get {
                return ResourceManager.GetString("Footer_ConnectServerToDownloadMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest version update required.
        /// </summary>
        public static string Footer_NeedUpdateMessage {
            get {
                return ResourceManager.GetString("Footer_NeedUpdateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected.
        /// </summary>
        public static string Footer_ServerStatus_Connected {
            get {
                return ResourceManager.GetString("Footer_ServerStatus_Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting.
        /// </summary>
        public static string Footer_ServerStatus_Connecting {
            get {
                return ResourceManager.GetString("Footer_ServerStatus_Connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection failed.
        /// </summary>
        public static string Footer_ServerStatus_Failed {
            get {
                return ResourceManager.GetString("Footer_ServerStatus_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting.
        /// </summary>
        public static string Footer_ServerStatus_Waiting {
            get {
                return ResourceManager.GetString("Footer_ServerStatus_Waiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Fail.
        /// </summary>
        public static string Inline_ConnecetionFail {
            get {
                return ResourceManager.GetString("Inline_ConnecetionFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected.
        /// </summary>
        public static string Inline_Connected {
            get {
                return ResourceManager.GetString("Inline_Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait a moment..
        /// </summary>
        public static string Inline_Connection_ConnectingMessage {
            get {
                return ResourceManager.GetString("Inline_Connection_ConnectingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⓘ The server connection remains active even after you restart the PC..
        /// </summary>
        public static string Inline_Connection_DefaultMessage {
            get {
                return ResourceManager.GetString("Inline_Connection_DefaultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⚠️ Unable to connect to the server. Check your internet connection..
        /// </summary>
        public static string Inline_Connection_ErrorMessage {
            get {
                return ResourceManager.GetString("Inline_Connection_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter server address and click [Connect]..
        /// </summary>
        public static string Inline_Connection_IdleMessage {
            get {
                return ResourceManager.GetString("Inline_Connection_IdleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⚠️ Unable to connect to the server. Check the server address and try again..
        /// </summary>
        public static string Inline_Connection_initErrorMessage {
            get {
                return ResourceManager.GetString("Inline_Connection_initErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server:.
        /// </summary>
        public static string Inline_Footer_ServerStatus {
            get {
                return ResourceManager.GetString("Inline_Footer_ServerStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⓘ Restart the program to change the language settings..
        /// </summary>
        public static string Inline_Language_DefaultMessage {
            get {
                return ResourceManager.GetString("Inline_Language_DefaultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ex) http://192.168.0.10 or http://example.com.
        /// </summary>
        public static string Input_Connection_DefaultServerAddress {
            get {
                return ResourceManager.GetString("Input_Connection_DefaultServerAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Input_Language {
            get {
                return ResourceManager.GetString("Input_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Address.
        /// </summary>
        public static string Input_ServerAddress {
            get {
                return ResourceManager.GetString("Input_ServerAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Connection.
        /// </summary>
        public static string Input_ServerConnection {
            get {
                return ResourceManager.GetString("Input_ServerConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must restart the program to change the language.
        ///Do you want to restart now?.
        /// </summary>
        public static string MessageBox_Apply_Language_Message {
            get {
                return ResourceManager.GetString("MessageBox_Apply_Language_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Settings.
        /// </summary>
        public static string MessageBox_Apply_Language_Title {
            get {
                return ResourceManager.GetString("MessageBox_Apply_Language_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting.
        /// </summary>
        public static string Status_Connecting {
            get {
                return ResourceManager.GetString("Status_Connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection failed.
        /// </summary>
        public static string Status_Fail {
            get {
                return ResourceManager.GetString("Status_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Tab_Home {
            get {
                return ResourceManager.GetString("Tab_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string Tab_Info {
            get {
                return ResourceManager.GetString("Tab_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Tab_Settings {
            get {
                return ResourceManager.GetString("Tab_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Tray_Button_Exit {
            get {
                return ResourceManager.GetString("Tray_Button_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Tray_Button_Open {
            get {
                return ResourceManager.GetString("Tray_Button_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected to the server..
        /// </summary>
        public static string Tray_ConnectedMessage {
            get {
                return ResourceManager.GetString("Tray_ConnectedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to connect to the server.
        /// </summary>
        public static string Tray_ConnectFailMessage {
            get {
                return ResourceManager.GetString("Tray_ConnectFailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to the server..
        /// </summary>
        public static string Tray_ConnectingMessage {
            get {
                return ResourceManager.GetString("Tray_ConnectingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not connected to the server..
        /// </summary>
        public static string Tray_IdleMessage {
            get {
                return ResourceManager.GetString("Tray_IdleMessage", resourceCulture);
            }
        }
    }
}
